export default {
    en: {
        "meta_section_title": "Document properties",
        "slices_section_title": "Slices",
        "annotations_section_title": "Notes & references",
        "document_title_label": "Document title",
        "document_id_label": "ID",
        "document_copyright_label": "Copyright notice",
        "create_slice": "Add a new slice",
        "create_annotation": "Add a new annotation",
        "no_slice_title": "Unnamed slice",
        'slice_type_markdown': "Rich Text (markdown)",
        'slice_type_kvlist': "Key-Value list",
        'slice_type_heading': "Heading",
        'slice_type_image': 'Image',
        'slice_type_table': "Table",
        'slice_type_graph': "Graph",
        'slice_title_field_label': "Slice title (n+0)",
        'slice_referenced_as_field_label': "Verbose reference anchor name",
        'readonly_slice': "The content of this slice is marked as not to be manually edited (`readonly`).",
        "kv_slice_key_label": "Label for key",
        "kv_slice_value_label": "Label for value",
        'presentation_none': "Inline presentation (default)",
        'presentation_figure': 'Figure',
        'presentation_aside': "Box",
        'annotation_id_label': "Annotation identifier",
        'annotation_id_helper': "You can refer to this annotation using the following string: ",
        'annotation_content_type_label': "Content type",
        'annotation_content_label': "Content",
        'slice_meta_type_sources': "Sources",
        'slice_meta_type_notes': "Notes",
        'slice_meta_type_alts': "Textual descriptions",
        'meta_editing_slice_button_label': 'Edit slice metadata',
        'previewing_slice_button_label': "Preview slice",
        'delete_slice_button_label': "Delete slice",
        'move_slice_up_button_label': "Push the slice towards the start",
        'move_slice_down_button_label': "Push the slice towards the end",
        'image_slice_thumbnails_details_label': "Thumbnails (optional)",
        'image_slice_source_label': 'Source (full resolution image)',
        'image_slice_fill_from_clipboard': "Fill from clipboard"

    },
    fr: {
        "meta_section_title": "Propriétés du document",
        "slices_section_title": "Tranches",
        "annotations_section_title": "Notes et références",
        "document_title_label": "Titre du document",
        "document_id_label": "ID",
        "document_copyright_label": "Avis de droit d'auteur",
        "create_slice": "Ajouter une tranche",
        "create_annotation": "Ajouter une annotation",
        "no_slice_title": "Tranche sans nom",
        'slice_type_markdown': "Rich Text (markdown)",
        'slice_type_kvlist': "Liste clé-valeur",
        'slice_type_heading': "En-tête",
        'slice_type_image': 'Image',
        'slice_type_table': "Tableau",
        'slice_type_graph': "Graphique",
        'slice_title_field_label': "Titre de la tranche (n+0)",
        'slice_referenced_as_field_label': "Verbose reference anchor name",
        'readonly_slice': "Le contenu de cette tranche est marqué comme ne devant pas être manuellement modifié (`readonly`).",
        "kv_slice_key_label": "Étiquette des clés",
        "kv_slice_value_label": "Étiquette des valeurs",
        'presentation_none': "Présentation au fil de la page (par défault)",
        'presentation_figure': 'Figure',
        'presentation_aside': "Box",
        'annotation_id_label': "Identifiant de l'annotation",
        'annotation_id_helper': "Vous pouvez référer à cette annotation en utilisant la chaine suivante : ",
        'annotation_content_type_label': "Type de contenu",
        'annotation_content_label': "Contenu",
        'slice_meta_type_sources': "Sources",
        'slice_meta_type_notes': "Notes",
        'slice_meta_type_alts': "Descriptions textuelles",
        'meta_editing_slice_button_label': 'Modifier les métadonnées de la tranche',
        'previewing_slice_button_label': "Aperçu de la tranche",
        'delete_slice_button_label': "Supprimer la tranche",
        'move_slice_up_button_label': "Pousser la tranche vers le début",
        'move_slice_down_button_label': "Pousser la tranche vers la fin",
        'image_slice_thumbnails_details_label': "Vignettes (cette section est facultative)",
        'image_slice_source_label': 'Source (image en pleine résolution)',
        'image_slice_fill_from_clipboard': "Fill from clipboard"

    }
}