export default {
    en: {
        "meta_section_title": "Document properties",
        "slices_section_title": "Slices",
        "document_title_label": "Document title",
        "document_id_label": "ID",
        "document_copyright_label": "Copyright notice",
        "create_slice": "Add a new slice",
        "no_slice_title": "Unnamed slice",
        'slice_type_markdown': "Rich Text (markdown)",
        'slice_type_kv': "Key-Value list",
        'slice_title_field_label': "Slice title",
        'readonly_slice': "The content of this slice is marked as not to be manually edited (`readonly`).",
        "kv_slice_key_label": "Label for key",
        "kv_slice_value_label": "Label for value",
    },
    fr: {
        "meta_section_title": "Propriétés du document",
        "slices_section_title": "Tranches",
        "document_title_label": "Titre du document",
        "document_id_label": "ID",
        "document_copyright_label": "Avis de droit d'auteur",
        "create_slice": "Ajouter une tranche",
        "no_slice_title": "Tranche sans nom",
        'slice_type_markdown': "Rich Text (markdown)",
        'slice_type_kv': "Liste clé-valeur",
        'slice_title_field_label': "Titre de la tranche",
        'readonly_slice': "Le contenu de cette tranche est marqué comme ne devant pas être manuellement modifié (`readonly`).",
        "kv_slice_key_label": "Étiquette des clés",
        "kv_slice_value_label": "Étiquette des valeurs",
    }
}