export default {
    en: {
        "close": "Close",
        "edit": "Edit",
        "structure_section_title": "Structure",
        "meta_section_title": "Document properties",
        "slices_section_title": "Slices",
        "annotations_section_title": "Notes & refs",
        "document_title_label": "Document title",
        "document_id_label": "ID",
        "document_copyright_label": "Copyright notice",
        "create_slice": "Add a new slice",
        "create_annotation": "Add a new annotation",
        "no_slice_title": "Unnamed slice",
        'slice_type_markdown': "Rich Text (markdown)",
        'slice_type_kvlist': "Key-Value list",
        'slice_type_heading': "Heading",
        'slice_type_bitmap': 'Bitmap',
        'slice_type_table': "Table",
        'slice_type_chart': "Chart",
        'slice_type_svg': 'SVG Vector',
        'slice_type_LaTeX': "LaTeX",
        'slice_type_html': "HTML",

        'slice_type_abbrev_markdown': "MKD",
        'slice_type_abbrev_kvlist': "KV",
        'slice_type_abbrev_heading': "H",
        'slice_type_abbrev_bitmap': 'BMP',
        'slice_type_abbrev_table': "TBL",
        'slice_type_abbrev_chart': "CHA",
        'slice_type_abbrev_svg': 'SVG',
        'slice_type_abbrev_LaTeX': "LTX",
        'slice_type_abbrev_html': "HTM",


        'advanced_slice_warning': "This type of slice is not recommended. Only use this type of slice when necessary. Are you sure you want to continue ?",
        'slice_title_field_label': "Title",
        'slice_referenced_as_field_label': "Anchor",
        'slice_id_hint': "This reference will only appear in the document's source code.",
        'readonly_slice': "The content of this slice is marked as not to be manually edited (`readonly`).",
        "kv_slice_display_labels_label": "Display labels",
        "kv_slice_key_label": "Label for key",
        "kv_slice_key_label": "Label for key",
        "kv_slice_value_label": "Label for value",
        'presentation_none': "Inline presentation (default)",
        'presentation_figure': 'Figure/Table (numbered)',
        'presentation_aside': "Box (Aside)",
        'annotation_id_label': "Annotation identifier",
        'annotation_id_helper': "You can refer to this annotation using the following string: ",
        'annotation_content_type_label': "Content type",
        'annotation_content_label': "Content",
        'annotation_auto_keep_organized_checkbox': "Enforce numerical order",
        'slice_meta_type_sources': "Sources",
        'slice_meta_type_notes': "Notes",
        'slice_meta_type_alts': "Textual descriptions",
        'meta_editing_slice_button_label': 'Edit slice metadata',
        'previewing_slice_button_label': "Preview slice",
        'delete_button_label': "Delete",
        'duplicate_slice_button_label': "Duplicate slice",
        'move_up_button_label': "Push the slice towards the start",
        'move_down_button_label': "Push the slice towards the end",
        'bitmap_slice_thumbnails_details_label': "Thumbnails (optional)",
        'bitmap_slice_source_label': 'Source (full resolution bitmap)',
        'bitmap_slice_fill_from_clipboard': "Fill from clipboard",
        'svg_slice_show_source_button_label': 'Source code',
        'svg_slice_show_more_options_button_label': 'SVG Tools',
        'data_table_visual_editor': 'Tabular data',
        'data_table_content_new': "Add values",
        'data_table_variables_editor': 'Variables',
        'data_table_variables_editor_var_new': "New variable",
        'data_table_variables_editor_var_new_key': "Enter the new variable key",
        'data_table_variables_editor_var_label': "Label",
        'data_table_variables_editor_var_type': "Content type",
        'data_table_variables_editor_var_is_descriptive': "Describes column contents.",
        'data_table_variables_editor_var_skip_chart': "Hide from chart",
        'data_table_entry_editor_var_skip_chart': "Display in chart",
        'data_table_variables_editor_var_group': "Group by label",
        'data_table_variables_editor_var_unit': "Unit",
        'data_table_variables_editor_var_chart_type': "Drawn as...",
        'data_table_variables_editor_advanced_toggle': "Advanced settings",
        'data_table_variables_editor_var_type_number': 'Number',
        'data_table_variables_editor_var_type_markdown': 'Rich text',
        'data_table_variables_editor_var_tension': "Tension",
        'data_table_variables_editor_var_tension_hint': "Determines the curve of the line. At 0 it's completely straight between points, at 0.4 it's balanced. Use `monotone` for the cubic interpolation mode.",
        'data_table_importer': 'Import',
        'data_table_importer_append_checkbox': "Replace existing table data",
        'data_table_importer_import_button': 'Import',
        'data_table_importer_var_on_label': "Location of variables",
        'data_table_importer_var_on_first_col': "First column",
        'data_table_importer_var_on_first_row': "First row",
        'data_table_editor_emphasize': "Emphasize",
        'data_table_editor_delete': "Delete",
        'data_table_has_no_units': "No variable in the table has a unit specified.",
        'paste_from_office': "Paste from Microsoft Office",
        'collapse_all': 'Collapse all',
        'expand_all': 'Expand all',
        'open_enhanced_preview': 'Open enhanced preview',
        'close_enhanced_preview': 'Close enhanced preview',
        'enhanced_preview_title': 'Enhanced preview',
        'svg_fit_tool': 'Fit',
        'svg_white_remover_tool': 'Remove white',
        'svg_sanitizer_tool': 'Remove forbidden characters',
        'editor_actions_preview': "Preview",
        'editor_actions_export': "Export",
        'editor_actions_source': "Source",
        'html_slice_should_remove_default_styles': "Remove default styles (Tailwind)",
        "append_structure_from_markdown": "Append structure from Markdown",
        "edit_source_code": "Edit source code",
        "stop_editing_source_code": "Stop editing source code",
        "apply": "Apply",
        "slice_source_code_warning_type_mismatch": "Changing the slice type from the source code may cause the editor to malfunction. A page reload might be necessary.",
        "data_table_variables_presentation_type": "Presentation style",
        "data_table_variables_presentation_type_auto": "Auto",
        "data_table_variables_presentation_type_accounting": "Accounting",
        "data_table_variables_presentation_type_text": "Text",
    },
    fr: {
        "close": "Fermer",
        "edit": "Éditer",
        "structure_section_title": "Structure",
        "meta_section_title": "Propriétés du document",
        "slices_section_title": "Tranches",
        "annotations_section_title": "Notes et réf.",
        "document_title_label": "Titre du document",
        "document_id_label": "ID",
        "document_copyright_label": "Avis de droit d'auteur",
        "create_slice": "Ajouter une tranche",
        "create_annotation": "Ajouter une annotation",
        "no_slice_title": "Tranche sans nom",
        'slice_type_markdown': "Rich Text (markdown)",
        'slice_type_kvlist': "Liste clé-valeur",
        'slice_type_heading': "En-tête",
        'slice_type_bitmap': 'Bitmap',
        'slice_type_table': "Tableau",
        'slice_type_chart': "Graphique",
        'slice_type_svg': 'SVG Vector',
        'slice_type_LaTeX': "LaTeX",
        'slice_type_html': "HTML",

        'slice_type_abbrev_markdown': "MKD",
        'slice_type_abbrev_kvlist': "CV",
        'slice_type_abbrev_heading': "ET",
        'slice_type_abbrev_bitmap': 'BMP',
        'slice_type_abbrev_table': "TBL",
        'slice_type_abbrev_chart': "GRA",
        'slice_type_abbrev_svg': 'SVG',
        'slice_type_abbrev_LaTeX': "LTX",
        'slice_type_abbrev_html': "HTM",

        'advanced_slice_warning': "Ce type de tranche n'est pas recommandé. Utilisez-le seulement lorsque nécessaire. Êtes-vous sûr de vouloir continuer ?",
        'slice_title_field_label': "Titre",
        'slice_referenced_as_field_label': "Ancre",
        'slice_id_hint': "Cette référence n'apparaîtra que dans le code source du document.",
        'readonly_slice': "Le contenu de cette tranche est marqué comme ne devant pas être manuellement modifié (`readonly`).",
        "kv_slice_display_labels_label": "Afficher les étiquettes.",
        "kv_slice_key_label": "Étiquette des clés",
        "kv_slice_value_label": "Étiquette des valeurs",
        'presentation_none': "Présentation au fil de la page (par défault)",
        'presentation_figure': 'Figure/tableau numéroté',
        'presentation_aside': "Boîte d'accompagnement (aside)",
        'annotation_id_label': "Identifiant de l'annotation",
        'annotation_id_helper': "Vous pouvez référer à cette annotation en utilisant la chaine suivante : ",
        'annotation_content_type_label': "Type de contenu",
        'annotation_content_label': "Contenu",
        'annotation_auto_keep_organized_checkbox': "Appliquer l'ordre numérique",
        'slice_meta_type_sources': "Sources",
        'slice_meta_type_notes': "Notes",
        'slice_meta_type_alts': "Descriptions textuelles",
        'meta_editing_slice_button_label': 'Modifier les métadonnées de la tranche',
        'previewing_slice_button_label': "Aperçu de la tranche",
        'delete_button_label': "Supprimer",
        'duplicate_slice_button_label': "Dupliquer la tranche",
        'move_up_button_label': "Pousser vers le début",
        'move_down_button_label': "Pousser vers la fin",
        'bitmap_slice_thumbnails_details_label': "Vignettes (cette section est facultative)",
        'bitmap_slice_source_label': 'Source (bitmap en pleine résolution)',
        'bitmap_slice_fill_from_clipboard': "Fill from clipboard",
        'svg_slice_show_source_button_label': 'Code source',
        'svg_slice_show_more_options_button_label': 'Outils pour SVG',
        'data_table_visual_editor': 'Données tabulaires',
        'data_table_content_new': "Nouvelles valeurs",
        'data_table_variables_editor': 'Variables',
        'data_table_variables_editor_var_new': "Nouvelle variable",
        'data_table_variables_editor_var_new_key': "Entrez la clé de la nouvelle variable.",
        'data_table_variables_editor_var_label': "Étiquette",
        'data_table_variables_editor_var_type': "Type de contenu",
        'data_table_variables_editor_var_is_descriptive': "Décrit le contenu de sa colonne.",
        'data_table_variables_editor_var_skip_chart': "Ne pas montrer dans le graphique",
        'data_table_entry_editor_var_skip_chart': "Montrer dans le graphique",
        'data_table_variables_editor_var_group': "Grouper avec l'étiquette",
        'data_table_variables_editor_var_unit': "Unité",
        'data_table_variables_editor_var_chart_type': "Dessiner sous la forme de...",
        'data_table_variables_editor_advanced_toggle': "Paramètres avancés",
        'data_table_variables_editor_var_type_number': 'Numérique',
        'data_table_variables_editor_var_type_markdown': 'Texte riche',
        'data_table_variables_editor_var_tension': "Tension",
        'data_table_variables_editor_var_tension_hint': "Détermine la courbe de la ligne. À 0 elle est entièrement droite entre les point, à 0.4 elle est balancée. Utilisez `monotone` pour le mode d'interpolation cubique.",
        'data_table_importer': 'Importer',
        'data_table_importer_append_checkbox': "Replace existing table data",
        'data_table_importer_import_button': 'Import',
        'data_table_importer_var_on_label': "Location of variables",
        'data_table_importer_var_on_first_col': "First column",
        'data_table_importer_var_on_first_row': "First row",
        'data_table_editor_emphasize': "Mettre en emphase",
        'data_table_editor_delete': "Supprimer",
        'data_table_has_no_units': "Aucune variable du tableau n'a d'unité spécifiée.",
        'paste_from_office': "Coller depuis Microsoft Office",
        'collapse_all': 'Tout réduire',
        'expand_all': 'Tout étendre',
        'open_enhanced_preview': 'Ouvrir l\'aperçu amélioré',
        'close_enhanced_preview': 'Fermer l\'aperçu amélioré',
        'enhanced_preview_title': 'Aperçu amélioré',
        'svg_fit_tool': 'Adapter la boîte',
        'svg_white_remover_tool': 'Enlever le blanc',
        'svg_sanitizer_tool': 'Filtrer les caractères interdits',
        'editor_actions_preview': "Aperçu",
        'editor_actions_export': "Exporter",
        'editor_actions_source': "Source",
        'html_slice_should_remove_default_styles': "Enlever les styles par défaut (Tailwind)",
        "append_structure_from_markdown": "Ajouter une structure depuis Markdown",
        "edit_source_code": "Éditer le code source",
        "stop_editing_source_code": "Arrêter l'édition du code source",
        "apply": "Appliquer",
        "slice_source_code_warning_type_mismatch": "Changer le type de tranche depuis le code-source peut entraîner un dysfonctionnement de l'éditeur. Un rechargement de la page pourrait être nécessaire.",
        "data_table_variables_presentation_type": "Style de présentation",
        "data_table_variables_presentation_type_auto": "Auto",
        "data_table_variables_presentation_type_accounting": "Comptabilité",
        "data_table_variables_presentation_type_text": "Texte",
    }
}