name: generate-pdf
on: 
  workflow_dispatch:
    inputs:
        input:
          description: 'A PBOML payload (YAML string).'
          required: true
        callback:
          description: 'URL to POST the artifacts to.'
          required: true
jobs:
  generate-page-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: npm i --save puppeteer
      - run: node ./.github/scripts/generate-pdf.js
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: pboml-gen-fr.pdf
          path: pboml-gen-fr.pdf
          retention-days: 1