name: generate-pdf
on: 
  workflow_dispatch:
    inputs:
        input:
          description: 'A PBOML payload (YAML string).'
          required: true
        callback:
          description: 'URL to POST the artifacts to.'
          required: true
jobs:
  generate-page-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sudo npm install -g puppeteer-pdf-wrapper
      - name: Generate EN pdf
        run: puppeteer-pdf-wrapper generate -u https://pboml-parser--parseur-pboml.s3.ca-central-1.amazonaws.com/index.html -n pbomlexample.pdf
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: pbomlexample.pdf
          path: pbomlexample.pdf
          retention-days: 1